version: 0.0
os: linux
files:
  - source: /AR_logo_3D.jpg
    destination: /home/ubuntu/myproject/media
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

